# This is a template for a Flutter project that streamlines the process of creating a new mobile App
# Built By Harith
# https://x.com/devHarithWick

name: flutter_template
description: "Template for all new Flutter Projects"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Used for local storage
  hive_flutter: ^1.1.0
  hive: ^2.2.3

  # Custom fonts
  google_fonts: ^6.2.1

  # State management
  flutter_bloc: ^8.1.6

  # Firebase dependencies
  firebase_core: ^3.5.0
  firebase_crashlytics: ^4.1.2
  cloud_functions: ^5.1.2
  firebase_storage: ^12.0.1
  firebase_auth: ^5.1.1
  firebase_messaging: ^15.0.3
  firebase_in_app_messaging: ^0.8.0+4
  firebase_analytics: ^11.3.2

  # Revenue Cat In-app purchases
  purchases_flutter: ^8.1.2
  purchases_ui_flutter: ^8.1.2

  # Used for env variables
  flutter_dotenv: ^5.1.0

  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Used to change the name and the package name of the app
  rename: ^3.0.2
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
